// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hills1
NumericMatrix hills1(NumericVector cv1, NumericVector cv2, double width1, double width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills1p1
NumericMatrix hills1p1(NumericVector cv1, NumericVector cv2, double width1, double width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1p1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1p1(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills1p2
NumericMatrix hills1p2(NumericVector cv1, NumericVector cv2, double width1, double width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1p2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1p2(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills1p12
NumericMatrix hills1p12(NumericVector cv1, NumericVector cv2, double width1, double width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1p12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1p12(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1
NumericVector hills3d1(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p1
NumericVector hills3d1p1(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1p1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p1(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p2
NumericVector hills3d1p2(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1p2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p2(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p3
NumericVector hills3d1p3(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1p3(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p3(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p12
NumericVector hills3d1p12(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1p12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p12(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p13
NumericVector hills3d1p13(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1p13(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p13(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p23
NumericVector hills3d1p23(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1p23(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p23(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p123
NumericVector hills3d1p123(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d1p123(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p123(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills2
NumericMatrix hills2(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills2(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills2p1
NumericMatrix hills2p1(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills2p1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills2p1(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills2p2
NumericMatrix hills2p2(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills2p2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills2p2(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills2p12
NumericMatrix hills2p12(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills2p12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills2p12(cv1, cv2, width1, width2, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2
NumericVector hills3d2(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p1
NumericVector hills3d2p1(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2p1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p1(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p2
NumericVector hills3d2p2(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2p2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p2(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p3
NumericVector hills3d2p3(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2p3(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p3(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p12
NumericVector hills3d2p12(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2p12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p12(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p13
NumericVector hills3d2p13(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2p13(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p13(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p23
NumericVector hills3d2p23(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2p23(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p23(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p123
NumericVector hills3d2p123(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills3d2p123(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p123(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills1d1
NumericVector hills1d1(NumericVector cv1, double width1, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1d1(SEXP cv1SEXP, SEXP width1SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1d1(cv1, width1, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills1d1p
NumericVector hills1d1p(NumericVector cv1, double width1, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1d1p(SEXP cv1SEXP, SEXP width1SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1d1p(cv1, width1, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills1d2
NumericVector hills1d2(NumericVector cv1, NumericVector width1, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1d2(SEXP cv1SEXP, SEXP width1SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1d2(cv1, width1, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills1d2p
NumericVector hills1d2p(NumericVector cv1, NumericVector width1, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer_hills1d2p(SEXP cv1SEXP, SEXP width1SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills1d2p(cv1, width1, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3d
NumericVector fe3d(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2d(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp1
NumericVector fe3dp1(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp1(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp2
NumericVector fe3dp2(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p2, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp2(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p2, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp3
NumericVector fe3dp3(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp3(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp12
NumericVector fe3dp12(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, double p2, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp12(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, p2, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp13
NumericVector fe3dp13(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp13(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp23
NumericVector fe3dp23(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p2, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp23(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p2, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp123
NumericVector fe3dp123(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, double p2, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp123(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, p2, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}

// fe2d
NumericVector fe2d(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, double x, double y, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2d(cv1, cv2, width1, width2, heights, x, y, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe2dp1
NumericVector fe2dp1(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, double x, double y, double p1, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2dp1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP p1SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp1(cv1, cv2, width1, width2, heights, x, y, p1, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe2dp2
NumericVector fe2dp2(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, double x, double y, double p2, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2dp2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP p2SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp2(cv1, cv2, width1, width2, heights, x, y, p2, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe2dp12
NumericVector fe2dp12(NumericVector cv1, NumericVector cv2, NumericVector width1, NumericVector width2, NumericVector heights, double x, double y, double p1, double p2, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe2dp12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe2dp12(cv1, cv2, width1, width2, heights, x, y, p1, p2, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe1d
NumericVector fe1d(NumericVector cv1, NumericVector width1, NumericVector heights, double x, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe1d(SEXP cv1SEXP, SEXP width1SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe1d(cv1, width1, heights, x, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe1dp
NumericVector fe1dp(NumericVector cv1, NumericVector width1, NumericVector heights, double x, double p1, int tmin, int tmax);
RcppExport SEXP _metadynminer_fe1dp(SEXP cv1SEXP, SEXP width1SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP p1SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe1dp(cv1, width1, heights, x, p1, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metadynminer_hills1", (DL_FUNC) &_metadynminer_hills1, 8},
    {"_metadynminer_hills1p1", (DL_FUNC) &_metadynminer_hills1p1, 8},
    {"_metadynminer_hills1p2", (DL_FUNC) &_metadynminer_hills1p2, 8},
    {"_metadynminer_hills1p12", (DL_FUNC) &_metadynminer_hills1p12, 8},
    {"_metadynminer_hills3d1", (DL_FUNC) &_metadynminer_hills3d1, 10},
    {"_metadynminer_hills3d1p1", (DL_FUNC) &_metadynminer_hills3d1p1, 10},
    {"_metadynminer_hills3d1p2", (DL_FUNC) &_metadynminer_hills3d1p2, 10},
    {"_metadynminer_hills3d1p3", (DL_FUNC) &_metadynminer_hills3d1p3, 10},
    {"_metadynminer_hills3d1p12", (DL_FUNC) &_metadynminer_hills3d1p12, 10},
    {"_metadynminer_hills3d1p13", (DL_FUNC) &_metadynminer_hills3d1p13, 10},
    {"_metadynminer_hills3d1p23", (DL_FUNC) &_metadynminer_hills3d1p23, 10},
    {"_metadynminer_hills3d1p123", (DL_FUNC) &_metadynminer_hills3d1p123, 10},
    {"_metadynminer_hills2", (DL_FUNC) &_metadynminer_hills2, 8},
    {"_metadynminer_hills2p1", (DL_FUNC) &_metadynminer_hills2p1, 8},
    {"_metadynminer_hills2p2", (DL_FUNC) &_metadynminer_hills2p2, 8},
    {"_metadynminer_hills2p12", (DL_FUNC) &_metadynminer_hills2p12, 8},
    {"_metadynminer_hills3d2", (DL_FUNC) &_metadynminer_hills3d2, 10},
    {"_metadynminer_hills3d2p1", (DL_FUNC) &_metadynminer_hills3d2p1, 10},
    {"_metadynminer_hills3d2p2", (DL_FUNC) &_metadynminer_hills3d2p2, 10},
    {"_metadynminer_hills3d2p3", (DL_FUNC) &_metadynminer_hills3d2p3, 10},
    {"_metadynminer_hills3d2p12", (DL_FUNC) &_metadynminer_hills3d2p12, 10},
    {"_metadynminer_hills3d2p13", (DL_FUNC) &_metadynminer_hills3d2p13, 10},
    {"_metadynminer_hills3d2p23", (DL_FUNC) &_metadynminer_hills3d2p23, 10},
    {"_metadynminer_hills3d2p123", (DL_FUNC) &_metadynminer_hills3d2p123, 10},
    {"_metadynminer_hills1d1", (DL_FUNC) &_metadynminer_hills1d1, 6},
    {"_metadynminer_hills1d1p", (DL_FUNC) &_metadynminer_hills1d1p, 6},
    {"_metadynminer_hills1d2", (DL_FUNC) &_metadynminer_hills1d2, 6},
    {"_metadynminer_hills1d2p", (DL_FUNC) &_metadynminer_hills1d2p, 6},
    {"_metadynminer_fe3d", (DL_FUNC) &_metadynminer_fe3d, 11},
    {"_metadynminer_fe3dp1", (DL_FUNC) &_metadynminer_fe3dp1, 12},
    {"_metadynminer_fe3dp2", (DL_FUNC) &_metadynminer_fe3dp2, 12},
    {"_metadynminer_fe3dp3", (DL_FUNC) &_metadynminer_fe3dp3, 12},
    {"_metadynminer_fe3dp12", (DL_FUNC) &_metadynminer_fe3dp12, 13},
    {"_metadynminer_fe3dp13", (DL_FUNC) &_metadynminer_fe3dp13, 13},
    {"_metadynminer_fe3dp23", (DL_FUNC) &_metadynminer_fe3dp23, 13},
    {"_metadynminer_fe3dp123", (DL_FUNC) &_metadynminer_fe3dp123, 14},
    {"_metadynminer_fe2d", (DL_FUNC) &_metadynminer_fe2d, 9},
    {"_metadynminer_fe2dp1", (DL_FUNC) &_metadynminer_fe2dp1, 10},
    {"_metadynminer_fe2dp2", (DL_FUNC) &_metadynminer_fe2dp2, 10},
    {"_metadynminer_fe2dp12", (DL_FUNC) &_metadynminer_fe2dp12, 11},
    {"_metadynminer_fe1d", (DL_FUNC) &_metadynminer_fe1d, 6},
    {"_metadynminer_fe1dp", (DL_FUNC) &_metadynminer_fe1dp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_metadynminer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
