# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hills1 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills1p1 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1p1', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills1p2 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1p2', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills1p12 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1p12', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills2 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills2', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills2p1 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills2p1', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills2p2 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills2p2', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills2p12 <- function(cv1, cv2, width1, width2, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills2p12', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, n, tmin, tmax)
}

hills1d1 <- function(cv1, width1, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1d1', PACKAGE = 'metadynminer', cv1, width1, heights, n, tmin, tmax)
}

hills1d1p <- function(cv1, width1, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1d1p', PACKAGE = 'metadynminer', cv1, width1, heights, n, tmin, tmax)
}

hills1d2 <- function(cv1, width1, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1d2', PACKAGE = 'metadynminer', cv1, width1, heights, n, tmin, tmax)
}

hills1d2p <- function(cv1, width1, heights, n, tmin, tmax) {
    .Call('_metadynminer_hills1d2p', PACKAGE = 'metadynminer', cv1, width1, heights, n, tmin, tmax)
}

fe2d <- function(cv1, cv2, width1, width2, heights, x, y, tmin, tmax) {
    .Call('_metadynminer_fe2d', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, tmin, tmax)
}

fe2dp1 <- function(cv1, cv2, width1, width2, heights, x, y, p1, tmin, tmax) {
    .Call('_metadynminer_fe2dp1', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, p1, tmin, tmax)
}

fe2dp2 <- function(cv1, cv2, width1, width2, heights, x, y, p2, tmin, tmax) {
    .Call('_metadynminer_fe2dp2', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, p2, tmin, tmax)
}

fe2dp12 <- function(cv1, cv2, width1, width2, heights, x, y, p1, p2, tmin, tmax) {
    .Call('_metadynminer_fe2dp12', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, p1, p2, tmin, tmax)
}

fe1d <- function(cv1, width1, heights, x, tmin, tmax) {
    .Call('_metadynminer_fe1d', PACKAGE = 'metadynminer', cv1, width1, heights, x, tmin, tmax)
}

fe1dp <- function(cv1, width1, heights, x, p1, tmin, tmax) {
    .Call('_metadynminer_fe1dp', PACKAGE = 'metadynminer', cv1, width1, heights, x, p1, tmin, tmax)
}

f2d <- function(cv1, cv2, width1, width2, heights, x, y, tmin, tmax) {
    .Call('_metadynminer_f2d', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, tmin, tmax)
}

f2dp1 <- function(cv1, cv2, width1, width2, heights, x, y, p1, tmin, tmax) {
    .Call('_metadynminer_f2dp1', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, p1, tmin, tmax)
}

f2dp2 <- function(cv1, cv2, width1, width2, heights, x, y, p2, tmin, tmax) {
    .Call('_metadynminer_f2dp2', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, p2, tmin, tmax)
}

f2dp12 <- function(cv1, cv2, width1, width2, heights, x, y, p1, p2, tmin, tmax) {
    .Call('_metadynminer_f2dp12', PACKAGE = 'metadynminer', cv1, cv2, width1, width2, heights, x, y, p1, p2, tmin, tmax)
}

f1d <- function(cv1, width1, heights, x, tmin, tmax) {
    .Call('_metadynminer_f1d', PACKAGE = 'metadynminer', cv1, width1, heights, x, tmin, tmax)
}

f1dp <- function(cv1, width1, heights, x, p1, tmin, tmax) {
    .Call('_metadynminer_f1dp', PACKAGE = 'metadynminer', cv1, width1, heights, x, p1, tmin, tmax)
}

