source("metadynminer.R")
#hillsf <- read.hills("HILLS_1.3_full", per=c(T,T))
hillsf <- read.hills("HILLS_AceProProNH2", per=c(F))
tfes<-fes1d(hillsf)
print("ok")
png("test.png")
#image(x=180*tfes$x/pi, y=180*tfes$y/pi, z=tfes$fes, axes=F)
#contour(x=180*tfes$x/pi, y=180*tfes$y/pi, z=tfes$fes, add=T)
#axis(1, at=-3:3*60)
#axis(2, at=-3:3*60)
#box()
print(tfes)
dev.off()


