source("metadynminer.R")
hillsf <- read.hills("HILLS_1.3_full", per=c(T,T))
#hillsf <- read.hills("HILLS_AceProProNH2", per=c(F))
tfes1<-fes2d(hillsf, tmax=9900)
tfes2<-fes2d(hillsf, tmin=9900, tmax=10000)
print("ok")
png("test.png")
#image(x=180*tfes$x/pi, y=180*tfes$y/pi, z=tfes$fes, axes=F)
#contour(x=180*tfes$x/pi, y=180*tfes$y/pi, z=tfes$fes, add=T)
#axis(1, at=-3:3*60)
#axis(2, at=-3:3*60)
#box()
print(tfes1)
print(tfes2)
print(tfes1+tfes2)
dev.off()


